"""
Export utilities for generating professional reports
Supports JSON and Markdown formats
"""
import json
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path


class ReportExporter:
    """Export discovery results to JSON and Markdown formats"""
    
    def __init__(self, results: Dict, session_id: str):
        self.results = results
        self.session_id = session_id
        self.timestamp = datetime.now()
    
    def export_to_markdown(self, output_path: str) -> str:
        """Export to Markdown format"""
        md_content = self._generate_markdown()
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return output_path
    
    def _generate_markdown(self) -> str:
        """Generate Markdown content"""
        summary = self.results.get('summary', {})
        answers = self.results.get('answers', [])
        missing = self.results.get('missing_information', [])
        
        md = f"""# Azure Landing Zone Discovery Report

**Session ID:** {self.session_id}  
**Generated:** {self.timestamp.strftime('%B %d, %Y at %I:%M %p')}  
**Completion:** {summary.get('completion_percentage', 0):.1f}%

---

## Executive Summary

- **Total Questions:** {summary.get('answered', 0)}/{summary.get('total_questions', 0)}
- **Documents Analyzed:** {summary.get('documents_analyzed', 0)}
- **Critical Questions Answered:** {summary.get('critical_questions', {}).get('answered', 0)}/{summary.get('critical_questions', {}).get('total', 0)}

---

## Discovery Findings

"""
        
        # Group answers by category
        by_category = {}
        for answer in answers:
            cat = answer['category']
            if cat not in by_category:
                by_category[cat] = []
            by_category[cat].append(answer)
        
        # Write each category
        for category, items in by_category.items():
            md += f"\n### {category}\n\n"
            for item in items:
                md += f"**Q: {item['question']}**  \n"
                md += f"A: {item['answer']}  \n"
                md += f"*Source: {item['source']} | Confidence: {item['confidence']:.0%}*\n\n"
        
        # Missing information
        if missing:
            md += "\n---\n\n## Missing Information\n\n"
            md += "The following information is still needed:\n\n"
            
            critical_missing = [m for m in missing if m['priority'] == 'critical']
            other_missing = [m for m in missing if m['priority'] != 'critical']
            
            if critical_missing:
                md += "### Critical Items\n\n"
                for item in critical_missing:
                    md += f"- **{item['question']}**\n"
                    if item.get('help_text'):
                        md += f"  - _{item['help_text']}_\n"
                md += "\n"
            
            if other_missing:
                md += "### Optional Items\n\n"
                for item in other_missing[:10]:  # Limit to 10
                    md += f"- {item['question']}\n"
                md += "\n"
        
        md += "\n---\n\n"
        md += "*This report was generated by Azure Landing Zone Discovery Agent*\n"
        
        return md
