"""
Export utilities for generating professional reports
Supports PDF, Word, Excel formats
"""
import json
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path


class ReportExporter:
    """Export discovery results to various formats"""
    
    def __init__(self, results: Dict, session_id: str):
        self.results = results
        self.session_id = session_id
        self.timestamp = datetime.now()
    
    def export_to_markdown(self, output_path: str) -> str:
        """Export to Markdown format"""
        md_content = self._generate_markdown()
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return output_path
    
    def _generate_markdown(self) -> str:
        """Generate Markdown content"""
        summary = self.results.get('summary', {})
        answers = self.results.get('answers', [])
        missing = self.results.get('missing_information', [])
        
        md = f"""# Azure Landing Zone Discovery Report

**Session ID:** {self.session_id}  
**Generated:** {self.timestamp.strftime('%B %d, %Y at %I:%M %p')}  
**Completion:** {summary.get('completion_percentage', 0):.1f}%

---

## Executive Summary

- **Total Questions:** {summary.get('answered', 0)}/{summary.get('total_questions', 0)}
- **Documents Analyzed:** {summary.get('documents_analyzed', 0)}
- **Critical Questions Answered:** {summary.get('critical_questions', {}).get('answered', 0)}/{summary.get('critical_questions', {}).get('total', 0)}

---

## Discovery Findings

"""
        
        # Group answers by category
        by_category = {}
        for answer in answers:
            cat = answer['category']
            if cat not in by_category:
                by_category[cat] = []
            by_category[cat].append(answer)
        
        # Write each category
        for category, items in by_category.items():
            md += f"\n### {category}\n\n"
            for item in items:
                md += f"**Q: {item['question']}**  \n"
                md += f"A: {item['answer']}  \n"
                md += f"*Source: {item['source']} | Confidence: {item['confidence']:.0%}*\n\n"
        
        # Missing information
        if missing:
            md += "\n---\n\n## Missing Information\n\n"
            md += "The following information is still needed:\n\n"
            
            critical_missing = [m for m in missing if m['priority'] == 'critical']
            other_missing = [m for m in missing if m['priority'] != 'critical']
            
            if critical_missing:
                md += "### Critical Items\n\n"
                for item in critical_missing:
                    md += f"- **{item['question']}**\n"
                    if item.get('help_text'):
                        md += f"  - _{item['help_text']}_\n"
                md += "\n"
            
            if other_missing:
                md += "### Optional Items\n\n"
                for item in other_missing[:10]:  # Limit to 10
                    md += f"- {item['question']}\n"
                md += "\n"
        
        md += "\n---\n\n"
        md += "*This report was generated by Azure Landing Zone Discovery Agent*\n"
        
        return md
    
    def export_to_pdf(self, output_path: str) -> str:
        """Export to PDF format (requires reportlab)"""
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
            from reportlab.lib import colors
            from reportlab.lib.enums import TA_CENTER, TA_LEFT
        except ImportError:
            # Fall back to Markdown if reportlab not available
            md_path = output_path.replace('.pdf', '.md')
            return self.export_to_markdown(md_path)
        
        doc = SimpleDocTemplate(output_path, pagesize=letter,
                                rightMargin=72, leftMargin=72,
                                topMargin=72, bottomMargin=18)
        
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#0078D4'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#0078D4'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        # Title
        story.append(Paragraph("Azure Landing Zone Discovery Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        
        # Metadata
        summary = self.results.get('summary', {})
        metadata = [
            ['Session ID:', self.session_id],
            ['Generated:', self.timestamp.strftime('%B %d, %Y at %I:%M %p')],
            ['Completion:', f"{summary.get('completion_percentage', 0):.1f}%"],
        ]
        
        t = Table(metadata, colWidths=[2*inch, 4*inch])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#333333')),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.5*inch))
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", heading_style))
        summary_data = [
            ['Metric', 'Value'],
            ['Total Questions', f"{summary.get('answered', 0)}/{summary.get('total_questions', 0)}"],
            ['Documents Analyzed', str(summary.get('documents_analyzed', 0))],
            ['Critical Questions', f"{summary.get('critical_questions', {}).get('answered', 0)}/{summary.get('critical_questions', {}).get('total', 0)}"],
            ['Answers from Documents', str(summary.get('answers_from_documents', 0))],
            ['Answers from User', str(summary.get('answers_from_user', 0))],
        ]
        
        t = Table(summary_data, colWidths=[3*inch, 2*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0078D4')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(t)
        story.append(PageBreak())
        
        # Discovery Findings
        story.append(Paragraph("Discovery Findings", heading_style))
        story.append(Spacer(1, 0.2*inch))
        
        answers = self.results.get('answers', [])
        by_category = {}
        for answer in answers:
            cat = answer['category']
            if cat not in by_category:
                by_category[cat] = []
            by_category[cat].append(answer)
        
        for category, items in by_category.items():
            story.append(Paragraph(category, styles['Heading3']))
            
            for item in items:
                # Question
                story.append(Paragraph(f"<b>Q: {item['question']}</b>", styles['Normal']))
                # Answer
                story.append(Paragraph(f"A: {item['answer']}", styles['Normal']))
                # Metadata
                story.append(Paragraph(
                    f"<i>Source: {item['source']} | Confidence: {item['confidence']:.0%}</i>",
                    styles['Normal']
                ))
                story.append(Spacer(1, 0.15*inch))
        
        doc.build(story)
        return output_path
    
    def export_to_excel(self, output_path: str) -> str:
        """Export to Excel format (requires openpyxl)"""
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill, Alignment
            from openpyxl.utils import get_column_letter
        except ImportError:
            # Fall back to Markdown
            md_path = output_path.replace('.xlsx', '.md')
            return self.export_to_markdown(md_path)
        
        wb = Workbook()
        
        # Summary sheet
        ws_summary = wb.active
        ws_summary.title = "Summary"
        
        # Headers
        ws_summary['A1'] = "Azure Landing Zone Discovery Report"
        ws_summary['A1'].font = Font(size=16, bold=True, color="0078D4")
        ws_summary.merge_cells('A1:D1')
        
        summary = self.results.get('summary', {})
        
        # Metadata
        row = 3
        metadata = [
            ('Session ID', self.session_id),
            ('Generated', self.timestamp.strftime('%B %d, %Y at %I:%M %p')),
            ('Completion', f"{summary.get('completion_percentage', 0):.1f}%"),
            ('', ''),
            ('Total Questions', f"{summary.get('answered', 0)}/{summary.get('total_questions', 0)}"),
            ('Documents Analyzed', summary.get('documents_analyzed', 0)),
            ('Critical Questions', f"{summary.get('critical_questions', {}).get('answered', 0)}/{summary.get('critical_questions', {}).get('total', 0)}"),
            ('Answers from Documents', summary.get('answers_from_documents', 0)),
            ('Answers from User', summary.get('answers_from_user', 0)),
        ]
        
        for label, value in metadata:
            if label:
                ws_summary[f'A{row}'] = label
                ws_summary[f'A{row}'].font = Font(bold=True)
                ws_summary[f'B{row}'] = value
            row += 1
        
        # Answers sheet
        ws_answers = wb.create_sheet("Answers")
        headers = ['Category', 'Priority', 'Question', 'Answer', 'Source', 'Confidence', 'Document']
        
        for col, header in enumerate(headers, 1):
            cell = ws_answers.cell(row=1, column=col, value=header)
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(start_color="0078D4", end_color="0078D4", fill_type="solid")
            cell.alignment = Alignment(horizontal="center", vertical="center")
        
        answers = self.results.get('answers', [])
        for row, answer in enumerate(answers, 2):
            ws_answers.cell(row=row, column=1, value=answer['category'])
            ws_answers.cell(row=row, column=2, value=answer['priority'].upper())
            ws_answers.cell(row=row, column=3, value=answer['question'])
            ws_answers.cell(row=row, column=4, value=answer['answer'])
            ws_answers.cell(row=row, column=5, value=answer['source'])
            ws_answers.cell(row=row, column=6, value=f"{answer['confidence']:.0%}")
            ws_answers.cell(row=row, column=7, value=answer.get('document_reference', ''))
        
        # Auto-size columns
        for col in range(1, 8):
            ws_answers.column_dimensions[get_column_letter(col)].width = 20
        
        # Missing information sheet
        ws_missing = wb.create_sheet("Missing Information")
        headers = ['Priority', 'Category', 'Question', 'Help Text']
        
        for col, header in enumerate(headers, 1):
            cell = ws_missing.cell(row=1, column=col, value=header)
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(start_color="C00000", end_color="C00000", fill_type="solid")
        
        missing = self.results.get('missing_information', [])
        for row, item in enumerate(missing, 2):
            ws_missing.cell(row=row, column=1, value=item['priority'].upper())
            ws_missing.cell(row=row, column=2, value=item['category'])
            ws_missing.cell(row=row, column=3, value=item['question'])
            ws_missing.cell(row=row, column=4, value=item.get('help_text', ''))
        
        # Auto-size columns
        for col in range(1, 5):
            ws_missing.column_dimensions[get_column_letter(col)].width = 25
        
        wb.save(output_path)
        return output_path
    
    def export_to_word(self, output_path: str) -> str:
        """Export to Word document (requires python-docx)"""
        try:
            from docx import Document
            from docx.shared import Inches, Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
        except ImportError:
            # Fall back to Markdown
            md_path = output_path.replace('.docx', '.md')
            return self.export_to_markdown(md_path)
        
        doc = Document()
        
        # Title
        title = doc.add_heading('Azure Landing Zone Discovery Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title.runs[0].font.color.rgb = RGBColor(0, 120, 212)
        
        # Metadata
        doc.add_paragraph(f"Session ID: {self.session_id}")
        doc.add_paragraph(f"Generated: {self.timestamp.strftime('%B %d, %Y at %I:%M %p')}")
        
        summary = self.results.get('summary', {})
        doc.add_paragraph(f"Completion: {summary.get('completion_percentage', 0):.1f}%")
        doc.add_paragraph()
        
        # Executive Summary
        doc.add_heading('Executive Summary', 1)
        doc.add_paragraph(f"Total Questions: {summary.get('answered', 0)}/{summary.get('total_questions', 0)}")
        doc.add_paragraph(f"Documents Analyzed: {summary.get('documents_analyzed', 0)}")
        doc.add_paragraph(f"Critical Questions Answered: {summary.get('critical_questions', {}).get('answered', 0)}/{summary.get('critical_questions', {}).get('total', 0)}")
        doc.add_paragraph()
        
        # Discovery Findings
        doc.add_heading('Discovery Findings', 1)
        
        answers = self.results.get('answers', [])
        by_category = {}
        for answer in answers:
            cat = answer['category']
            if cat not in by_category:
                by_category[cat] = []
            by_category[cat].append(answer)
        
        for category, items in by_category.items():
            doc.add_heading(category, 2)
            
            for item in items:
                p = doc.add_paragraph()
                p.add_run(f"Q: {item['question']}").bold = True
                
                doc.add_paragraph(f"A: {item['answer']}")
                
                meta = doc.add_paragraph(f"Source: {item['source']} | Confidence: {item['confidence']:.0%}")
                meta.runs[0].font.italic = True
                meta.runs[0].font.size = Pt(9)
                
                doc.add_paragraph()
        
        # Missing Information
        missing = self.results.get('missing_information', [])
        if missing:
            doc.add_page_break()
            doc.add_heading('Missing Information', 1)
            
            critical = [m for m in missing if m['priority'] == 'critical']
            if critical:
                doc.add_heading('Critical Items', 2)
                for item in critical:
                    p = doc.add_paragraph(item['question'], style='List Bullet')
                    if item.get('help_text'):
                        doc.add_paragraph(item['help_text'], style='List Bullet 2')
        
        doc.save(output_path)
        return output_path
